// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FavouritesbtnController from "./favouritesbtn_controller"
application.register("favouritesbtn", FavouritesbtnController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
